setwd("C:/coursera/Documents")
qdata <- read.table("household_power_consumption.txt",sep=";", header = TRUE)
qdata$Date <- as.Date(qdata$Date, format = "%d/%m/%Y")
library(dplyr)
reqddata <- filter(qdata,qdata$Date >= "2007-02-01" & qdata$Date <= "2007-02-02" )
reqddata$Global_active_power <- as.numeric(as.character(reqddata$Global_active_power))
png(file = "plot1.png")
hist(reqddata$Global_active_power, col = "red", ylab = "Frequency", xlab = "Global Active Power (kilowatts)", main= "Global Active Power")
dev.off()