setwd("C:/coursera/Documents")
qdata <- read.table("household_power_consumption.txt",sep=";", header = TRUE)
qdata$Date <- as.Date(qdata$Date, format = "%d/%m/%Y")
library(dplyr)
reqddata <- filter(qdata,qdata$Date >= "2007-02-01" & qdata$Date <= "2007-02-02" )
reqddata$Global_active_power <- as.numeric(as.character(reqddata$Global_active_power))
reqddata$datetime <- paste(reqddata$Date, as.character.POSIXt(reqddata$Time))
reqddata$datetime <- as.POSIXct(reqddata$datetime)
png(file = "plot2.png")
plot(values,reqddata$Global_active_power, ylab = "Global Active Power (kilowatts)", pch =".")
lines(values,reqddata$Global_active_power, ylab = "Global Active Power (kilowatts)")
dev.off()